version: "3"
services:
  application:
    build:
      args:
        user: ${SO_DOCKER_USER}
        uid: 1000
      context: ${PWD}/docker-compose/application
    working_dir: /var/www
    volumes:
      - ${PWD}/application:/var/www
    networks:
      - rede

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${USER_DB}
      MYSQL_ROOT_PASSWORD: ${USER_PASS}
    volumes:
      - mysqlvolume:/var/lib/mysql
    networks:
      - rede
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ${PWD}/application:/var/www
      - ${PWD}/docker-compose/nginx/conf/:/etc/nginx/conf.d/
    networks:
      - rede

  log-processor:
    image: php:8.2-cli
    volumes:
      - ./log-processor:/script
    command:
      php /script/processor.php
    networks:
      - rede

volumes:
  mysqlvolume:

networks:
  rede:
    driver: bridge
